// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGameList.Models;

namespace VideoGameList.Migrations
{
    [DbContext(typeof(VideoGameContext))]
    [Migration("20220406223735_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VideoGameList.Models.ESRB", b =>
                {
                    b.Property<string>("ESRBId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ESRBId");

                    b.ToTable("ESRB");

                    b.HasData(
                        new
                        {
                            ESRBId = "E",
                            Name = "Everyone"
                        },
                        new
                        {
                            ESRBId = "E 10+",
                            Name = "Everyone 10+"
                        },
                        new
                        {
                            ESRBId = "T",
                            Name = "Teen"
                        },
                        new
                        {
                            ESRBId = "M",
                            Name = "Mature"
                        },
                        new
                        {
                            ESRBId = "A",
                            Name = "Adults"
                        },
                        new
                        {
                            ESRBId = "RP",
                            Name = "Rating Pending"
                        });
                });

            modelBuilder.Entity("VideoGameList.Models.VideoGame", b =>
                {
                    b.Property<int>("VideoGameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ESRBId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VideoGameId");

                    b.HasIndex("ESRBId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            VideoGameId = 1,
                            ESRBId = "M",
                            Genre = "Action RPG",
                            Rating = 5,
                            ReleaseDate = new DateTime(2019, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tom Clancy's The Division 2"
                        },
                        new
                        {
                            VideoGameId = 2,
                            ESRBId = "M",
                            Genre = "Action Adventure",
                            Rating = 5,
                            ReleaseDate = new DateTime(2013, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Grand Theft Auto V"
                        });
                });

            modelBuilder.Entity("VideoGameList.Models.VideoGame", b =>
                {
                    b.HasOne("VideoGameList.Models.ESRB", "ESRB")
                        .WithMany()
                        .HasForeignKey("ESRBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
